
platform :ios, '9.0'

target 'APISample4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'KeychainAccess'
  pod 'RealmSwift'
  pod 'ReachabilitySwift', '~> 3'
  pod 'SDWebImage', '~>3.8'
  pod 'SVProgressHUD'
  pod 'R.swift'
  pod 'VTAcknowledgementsViewController'
  

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end