
platform :ios, '9.0'

target 'APISample3' do
  
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'KeychainAccess'
  pod 'RealmSwift'
  pod 'ReachabilitySwift', '~> 3'

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
